---
- name: Install WowUp addon manager from AUR
  shell: yay -S --noconfirm --needed wowup-cf-bin
  become_user: "{{ local_user }}"
  register: result
  changed_when: "'installing' in result.stdout"

- name: Install umu-launcher
  pacman:
    name: umu-launcher
    state: present

- name: Create games directory
  file:
    path: "{{ ansible_facts['user_dir'] }}/Games"
    state: directory
    mode: '0755'

- name: Download Battle.net installer
  command: >
    curl -fLo {{ ansible_facts['user_dir'] }}/Games/Battle.net-Setup.exe
    -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    https://downloader.battle.net/download/getInstaller?os=win&installer=Battle.net-Setup.exe
  args:
    creates: "{{ ansible_facts['user_dir'] }}/Games/Battle.net-Setup.exe"