---
- name: Install yay dependencies
  pacman:
    name:
      - git
      - go
    state: present

- name: Clone yay repository
  git:
    repo: https://github.com/Jguer/yay.git
    dest: /tmp/yay
    depth: 1

- name: Build and install yay
  command: cd /tmp/yay && makepkg -sic --noconfirm
  creates: /usr/bin/yay