---
- name: Personal applications
  hosts: localhost
  connection: local
  become: true
  vars:
    local_user: "{{ lookup('env', 'SUDO_USER') | default('') }}"
  pre_tasks:
    - name: Ensure playbook is run with sudo
      assert:
        that: local_user != ''
        fail_msg: "local_user is empty. Run with sudo, not as root directly."
  roles:
    - home-setup
    - dotfiles
    - matugen
    - zen-browser
    - screenshot
    - fonts-personal
    - dev-tools
