---
- name: Personal applications
  hosts: local
  become: true
  vars:
    local_user: "{{ ansible_user }}"
  roles:
    - home-setup
    - dotfiles
    - matugen
    - zen-browser
    - screenshot
    - fonts-personal
    - dev-tools
