---
- name: Bootstrap collections
  hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Install kewlfft.aur collection system-wide
      command: ansible-galaxy collection install kewlfft.aur -p /usr/share/ansible/collections
      args:
        creates: /usr/share/ansible/collections/ansible_collections/kewlfft/aur

- name: Install Hyprland
  hosts: localhost
  connection: local
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  roles:
    - yay
    - zen-browser
    - theming
    - screenshot
    - hyprland
    - nvidia
    - kitty
    - battlenet

- name: Install system packages
  hosts: localhost
  connection: local
  become: true
  roles:
    - fonts
    - zsh
    - awww
    - bluetooth
    - audio
    - thunar
    - polkit