---
- name: Check whether matugen is installed
  command: pacman -Q matugen-bin
  register: matugen_query
  changed_when: false
  failed_when: false

- name: Install matugen from AUR
  command: yay -S --noconfirm --needed matugen-bin
  become_user: "{{ local_user }}"
  when: matugen_query.rc != 0
