---
- name: Install screenshot dependencies
  pacman:
    name:
      - grim
      - slurp
    state: present

- name: Install AUR screenshot tools
  shell: yay -S --noconfirm --needed {{ item }}
  become_user: "{{ local_user }}"
  register: result
  changed_when: "'installing' in result.stdout"
  loop:
    - hyprquickframe
    - hyprshot
