---
- name: Install ccache
  pacman:
    name: ccache
    state: present

- name: Deploy optimized makepkg.conf
  template:
    src: makepkg.conf.j2
    dest: /etc/makepkg.conf
    owner: root
    group: root
    mode: '0644'
