---
- name: Install desktop utility packages
  pacman:
    name:
      - brightnessctl
      - playerctl
      - cliphist
      - wl-clipboard
      - thunar
      - thunar-volman
      - gvfs
    state: present

- name: Install AUR packages
  shell: yay -S --noconfirm --needed {{ item }}
  become_user: "{{ local_user }}"
  register: result
  changed_when: "'installing' in result.stdout"
  loop:
    - localsend-bin
    - wowup-cf-bin
