---
- name: Create standard home directories
  file:
    path: "/home/{{ local_user }}/{{ item }}"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0755'
  loop: "{{ home_directories }}"
