---
- name: Install nodejs and npm
  pacman:
    name:
      - nodejs
      - npm
    state: present

- name: Install Claude Code
  shell: npm install -g @anthropic-ai/claude-code
  args:
    creates: /usr/lib/node_modules/@anthropic-ai/claude-code/package.json


