---
- name: Install Liberation fonts (metric-compatible with Microsoft)
  pacman:
    name: ttf-liberation
    state: present

- name: Install Inter font
  pacman:
    name: inter-font
    state: present

- name: Install Apple emoji font from AUR
  command: yay -S --noconfirm --needed ttf-apple-emoji
  args:
    creates: /usr/share/fonts/TTF/AppleColorEmoji.ttf
